#!/usr/bin/env bash
./shell-scripts/clean

# compile C source to wasm on docker container
docker run -it --name wasm-builder \
  --mount type=bind,source="$(pwd)"/built-wasm,target=/built-wasm \
  --mount type=bind,source="$(pwd)"/src/c,target=/source \
  wasm-builder-image \
  /source/compile-for-web