#!/usr/bin/env bash
set -eu

./shell-scripts/clean

# compile C source to wasm on docker container
docker run -it --name wasm-builder \
  --mount type=bind,source="$(pwd)"/built-wasm,target=/built-wasm \
  --mount type=bind,source="$(pwd)"/src/c,target=/source \
  wasm-builder-image \
  /source/compile-for-tests

# using --forceExit for jest because otherwise it complains about the pthread workers causing "open handles" -
# possibly related - https://github.com/emscripten-core/emscripten/issues/12801
node ${DEBUG:+--inspect-brk} --experimental-wasm-threads node_modules/.bin/jest --forceExit test/wasm.test.js