#!/usr/bin/env bash
set -eu

# if there's already a container with the same name, remove it (it's probably from the last time we ran this script)
if [[ $(docker ps -aq --filter 'name=wasm-builder') ]]
then
  docker rm wasm-builder
fi

# make sure output directory exists on host
mkdir -p built-wasm

# clear output directory on host
rm -rf built-wasm/*

# compile C source to wasm on docker container
docker run -it --name wasm-builder \
  --mount type=bind,source="$(pwd)"/built-wasm,target=/built-wasm \
  --mount type=bind,source="$(pwd)"/src/c,target=/source \
  wasm-builder-image \
  /source/compile-for-tests

yarn jest test/wasm.test.js